export const ERROR_CODES = Object.freeze({
    INVALID_MINUTE_OF_DAY: 'INVALID_MINUTE_OF_DAY',
    INVALID_POSITIVE_MINUTES: 'INVALID_POSITIVE_MINUTES',
    INVALID_CONFIGURED_LIMIT: 'INVALID_CONFIGURED_LIMIT',
    INVALID_LOCAL_DATE: 'INVALID_LOCAL_DATE',
    INVALID_WEEKDAY: 'INVALID_WEEKDAY',
    INVALID_INSTANT: 'INVALID_INSTANT',
    INVALID_SEMANTIC_KEY: 'INVALID_SEMANTIC_KEY',
    INVALID_SCHEMA_VERSION: 'INVALID_SCHEMA_VERSION',
    INVALID_RHYTHM: 'INVALID_RHYTHM',
    INVALID_WORK_BLOCK: 'INVALID_WORK_BLOCK',
    OVERLAPPING_WORK_BLOCKS: 'OVERLAPPING_WORK_BLOCKS',
    EMPTY_WEEKDAYS: 'EMPTY_WEEKDAYS',
    CAPABILITY_NOT_CONFIRMED: 'CAPABILITY_NOT_CONFIRMED',
    INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
    UNKNOWN_TAG: 'UNKNOWN_TAG'
});

export function domainError(code, details) {
    return Object.freeze({
        tag: 'DomainError',
        code: code,
        details: details
    });
}

