export const ERROR_CODES = Object.freeze({
    INVALID_MINUTE_OF_DAY: 'INVALID_MINUTE_OF_DAY',
    INVALID_POSITIVE_MINUTES: 'INVALID_POSITIVE_MINUTES',
    INVALID_CONFIGURED_LIMIT: 'INVALID_CONFIGURED_LIMIT',
    INVALID_LOCAL_DATE: 'INVALID_LOCAL_DATE',
    INVALID_WEEKDAY: 'INVALID_WEEKDAY',
    INVALID_INSTANT: 'INVALID_INSTANT',
    INVALID_SEMANTIC_KEY: 'INVALID_SEMANTIC_KEY',
    INVALID_SCHEMA_VERSION: 'INVALID_SCHEMA_VERSION',
    INVALID_RHYTHM: 'INVALID_RHYTHM',
    INVALID_WORK_BLOCK: 'INVALID_WORK_BLOCK',
    OVERLAPPING_WORK_BLOCKS: 'OVERLAPPING_WORK_BLOCKS',
    EMPTY_WEEKDAYS: 'EMPTY_WEEKDAYS',
    EMPTY_WORK_BLOCKS: 'EMPTY_WORK_BLOCKS',
    INVALID_SCHEDULE_SETTINGS: 'INVALID_SCHEDULE_SETTINGS',
    INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
    INVALID_UTC_OFFSET: 'INVALID_UTC_OFFSET',
    INVALID_SNAPSHOT: 'INVALID_SNAPSHOT',
    UNSUPPORTED_SCHEMA_VERSION: 'UNSUPPORTED_SCHEMA_VERSION',
    CAPABILITY_NOT_CONFIRMED: 'CAPABILITY_NOT_CONFIRMED',
    INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
    NOTHING_TO_SKIP: 'NOTHING_TO_SKIP',
    REMINDER_NOT_EXPECTED: 'REMINDER_NOT_EXPECTED',
    REMINDER_REGISTRATION_FAILED: 'REMINDER_REGISTRATION_FAILED',
    REMINDER_LIST_UNAVAILABLE: 'REMINDER_LIST_UNAVAILABLE',
    REMINDER_FIRED_TOO_EARLY: 'REMINDER_FIRED_TOO_EARLY',
    STALE_REMINDER_CALLBACK: 'STALE_REMINDER_CALLBACK',
    UNKNOWN_COMMAND: 'UNKNOWN_COMMAND',
    UNKNOWN_EVENT: 'UNKNOWN_EVENT',
    UNKNOWN_TAG: 'UNKNOWN_TAG',
    UNKNOWN_EFFECT: 'UNKNOWN_EFFECT'
});

export function domainError(code, details) {
    return Object.freeze({
        tag: 'DomainError',
        code: code,
        details: details
    });
}

